export const post = {
  id: "MENU_POST",
  path: "",
  isPublic: false,
  icon: "ApartmentSharpIcon",
  text: "QL chuyển phát bưu kiện",
  child: [
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "DS phương tiện",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "DS khách hàng",
      child: [],
    },
    {
      id: "",
      path: "/postoffice/list",
      isPublic: false,
      icon: "StarBorder",
      text: "DS bưu cục",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "DS đơn hàng chuyển phát",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "Tạo mới đợt chuyển phát",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "DS đợt chuyển phát",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "Lập kế hoạch thu gom bưu kiện",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: false,
      icon: "StarBorder",
      text: "Lập kế hoạch phát bưu kiện",
      child: [],
    },
  ],
};
