export const ProgrammingContestMenuConfig = {
  id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT",
  path: "",
  isPublic: false,
  icon: "LocalLibraryIcon",
  text: "Programming Contest",
  child: [
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_REGISTER_CLASS",
      path: "/programming-contest/list-problems",
      isPublic: false,
      icon: null,
      text: "Problem",
      child: [],
    },
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_REGISTER_CLASS",
      path: "/programming-contest/create-problem",
      isPublic: false,
      icon: null,
      text: "Create Problem",
      child: [],
    },
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_REGISTER_CLASS",
      path: "/programming-contest/contest",
      isPublic: false,
      icon: null,
      text: "Contest",
      child: [],
    },
    {
      id: "MENU_EDUCATION_LEARNING_MANAGEMENT_STUDENT_REGISTER_CLASS",
      path: "/programming-contest/ide",
      isPublic: false,
      icon: null,
      text: "IDE",
      child: [],
    },
  ],
};
