export const salereport = {
  id: "MENU_SALES_REPORT",
  path: "",
  isPublic: false,
  icon: "FormatListNumberedIcon",
  text: "Báo cáo bán hàng",
  child: [
    {
      id: "",
      path: "/report-group/sale-reports-by-date",
      isPublic: true,
      icon: "StarBorder",
      text: "Doanh số theo ngày",
      child: [],
    },
    {
      id: "",
      path: "/report-group/sale-reports-by-customer",
      isPublic: true,
      icon: "StarBorder",
      text: "Doanh số theo khách hàng",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "Doanh số theo nhà phân phối",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "Doanh số theo nhân viên bán hàng",
      child: [],
    },
    {
      id: "",
      path: "/report-group/sale-reports-by-product",
      isPublic: true,
      icon: "StarBorder",
      text: "Doanh số theo sản phẩm",
      child: [],
    },
  ],
};
