export const salesroute = {
  id: "MENU_SALES_ROUTE",
  path: "",
  isPublic: false,
  icon: "LocalGroceryStoreIcon",
  text: "Tuyến bán hàng",
  child: [
    {
      id: "",
      path: "/salesman/list",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách NVBH",
      child: [],
    },
    {
      id: "",
      path: "/salesman/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Tạo mới NVBH",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách khách hàng",
      child: [],
    },
    {
      id: "",
      path: "/salesroutes/plan",
      isPublic: true,
      icon: "StarBorder",
      text: "Kế hoạch tuyến",
      child: [],
    },
    {
      id: "",
      path: "/salesroutes/configs",
      isPublic: true,
      icon: "StarBorder",
      text: "Cấu hình tuyến",
      child: [],
    },
    {
      id: "",
      path: "/salesroutes/plan/period/detail",
      isPublic: true,
      icon: "StarBorder",
      text: "Chi tiết tuyến",
      child: [],
    },
    {
      id: "",
      path: "/salesroutes/salesman-checkin-routes",
      isPublic: true,
      icon: "StarBorder",
      text: "Lịch sử check-in tuyến",
      child: [],
    },
  ],
};
