export const teachingassignment = {
  id: "MENU_EDUCATION_TEACHING_ASSIGNMENT",
  path: "",
  isPublic: false,
  icon: "AirportShuttleIcon",
  text: "Phân công giảng dạy",
  child: [
    {
      id: "MENU_EDUCATION_VIEW_LIST_SEMESTER",
      path: "/edu/semester",
      isPublic: false,
      icon: "StarBorder",
      text: "DS học kì",
      child: [],
    },
    {
      id: "MENU_EDUCATION_VIEW_LIST_COURSE",
      path: "/edu/courses/list",
      isPublic: false,
      icon: "StarBorder",
      text: "DS môn học",
      child: [],
    },
    {
      id: "MENU_EDUCATION_VIEW_LIST_TEACHER",
      path: "/edu/teachers/list",
      isPublic: false,
      icon: "StarBorder",
      text: "DS giảng viên",
      child: [],
    },
    {
      id: "MENU_EDUCATION_VIEW_LIST_CLASS",
      path: "/edu/classes-list",
      isPublic: false,
      icon: "StarBorder",
      text: "DS lớp",
      child: [],
    },
    {
      id: "MENU_EDUCATION_VIEW_LIST_ASSIGNMENT",
      path: "/edu/assignment",
      isPublic: false,
      icon: "StarBorder",
      text: "DS phân công",
      child: [],
    },
    {
      id: "MENU_EDUCATION_ASSIGNMENT_EXECUTION",
      path: "/edu/solve",
      isPublic: false,
      icon: "StarBorder",
      text: "Tiến hành phân công",
      child: [],
    },

    {
      id: "MENU_EDUCATION_ASSIGNMENT_EXECUTION",
      path: "/edu/class/register",
      isPublic: false,
      icon: null,
      text: "Đăng ký lớp",
      child: [],
    },
    {
      id: "MENU_EDUCATION_ASSIGNMENT_EXECUTION",
      path: "/edu/student/class/list",
      isPublic: false,
      icon: null,
      text: "Danh sách lớp",
      child: [],
    },
    {
      id: "MENU_EDUCATION_ASSIGNMENT_EXECUTION",
      path: "/edu/teacher/class/list",
      isPublic: false,
      icon: null,
      text: "DS lớp giảng viên",
      child: [],
    },
    
  ],
};
