export const teachingassignment = {
  id: "MENU_TEACHING_ASSIGNMENT",
  path: "",
  isPublic: true,
  icon: "AirportShuttleIcon",
  text: "Phân công giảng dạy",
  child: [
    {
      id: "",
      path: "/edu/semester",
      isPublic: true,
      icon: "StarBorder",
      text: "DS học kì",
      child: [],
    },
    {
      id: "",
      path: "/edu/courses-list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS môn học",
      child: [],
    },
    {
      id: "",
      path: "/edu/teachers-list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS giáo viên",
      child: [],
    },
    {
      id: "",
      path: "/edu/classes-list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS lớp",
      child: [],
    },
    {
      id: "",
      path: "/edu/assignment",
      isPublic: true,
      icon: "StarBorder",
      text: "DS phân công",
      child: [],
    },
    {
      id: "",
      path: "/edu/solve",
      isPublic: true,
      icon: "StarBorder",
      text: "Tiến hành phân công",
      child: [],
    },
  ],
};
