export const tmscontainer = {
  id: "MENU_TMS_CONTAINER",
  path: "",
  isPublic: false,
  icon: "AirportShuttleIcon",
  text: "Vận chuyển container",
  child: [
    {
      id: "",
      path: "/portfunc/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới bến cảng",
      child: [],
    },
    {
      id: "",
      path: "/portfunc/list",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách bến cảng",
      child: [],
    },
    {
      id: "",
      path: "/depottruckfunc/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới bãi đầu kéo",
      child: [],
    },
    {
      id: "",
      path: "/depottruckfunc/list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS bãi đầu kéo",
      child: [],
    },
    {
      id: "",
      path: "/depottrailerfunc/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới bãi mooc",
      child: [],
    },
    {
      id: "",
      path: "/depottrailerfunc/list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS bãi rơ mooc",
      child: [],
    },
    {
      id: "",
      path: "/depotcontainerfunc/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới bãi container",
      child: [],
    },
    {
      id: "",
      path: "/depotcontainerfunc/list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS bãi container",
      child: [],
    },
    {
      id: "",
      path: "/containerfunc/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Tạo mới container",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/containerfunc/list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS container",
      child: [],
    },
    {
      id: "",
      path: "/trailerfunc/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới rơ mooc",
      child: [],
    },
    {
      id: "",
      path: "/trailerfunc/list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS rơ mooc",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/create-request-transport-container-empty",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm yêu cầu chuyển container rỗng từ kho về bãi",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/list-request-transport-container-empty",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách đơn vận chuyển container rỗng từ kho đến bãi",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/create-request-transport-container-empty-export",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm yêu cầu chuyển container rỗng từ bãi về kho",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/list-request-transport-container-empty-export",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách đơn vận chuyển container rỗng từ bãi đến kho",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/create-request-transport-full-export",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới yêu cầu chuyển container đầy hàng từ kho ra cảng",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/list-request-transport-full-export",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách đơn vận chuyển container đầy hàng từ kho ra cảng ",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "DS đơn vận chuyển import empty",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/create-request-transport-container-to-warehouse",
      isPublic: true,
      icon: "StarBorder",
      text: "Thêm mới yêu cầu vận chuyển container đến kho",
      child: [],
    },
    {
      id: "",
      path: "/transport-group/list-request-transport-container-to-warehouse",
      isPublic: true,
      icon: "StarBorder",
      text: "Danh sách đơn vận chuyển container đầy đến kho",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "DS đơn chuyển kho",
      child: [],
    },
  ],
};
