export const transport = {
  //id: "MENU_TRANSPORT",
  id: "MENU_TMS",
  path: "",
  isPublic: false,
  icon: "AirportShuttleIcon",
  text: "QL Vận chuyển",
  child: [
    {
      id: "",
      path: "/vehicle-group/vehicle",
      isPublic: true,
      icon: "StarBorder",
      text: "DS Xe",
      child: [],
    },
    {
      id: "",
      path: "/driver-group/driver/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Tạo mới Tài xế",
      child: [],
    },
    {
      id: "",
      path: "/driver-group/driver/list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS Tài xế",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "DS khách hàng",
      child: [],
    },
    {
      id: "",
      path: "/shipment-group/shipment",
      isPublic: true,
      icon: "StarBorder",
      text: "DS đơn hàng vận chuyển",
      child: [],
    },
    {
      id: "",
      path: "/delivery-plan/create",
      isPublic: true,
      icon: "StarBorder",
      text: "Tạo mới đợt giao hàng",
      child: [],
    },
    {
      id: "",
      path: "/delivery-group/delivery-plan-list",
      isPublic: true,
      icon: "StarBorder",
      text: "DS đợt giao hàng",
      child: [],
    },
    {
      id: "",
      path: "",
      isPublic: true,
      icon: "StarBorder",
      text: "Lập kế hoạch giao hàng",
      child: [],
    },
    {
      id: "",
      path: "/config-group/solver-config-param",
      isPublic: true,
      icon: "StarBorder",
      text: "Cấu hình bộ giải",
      child: [],
    },
  ],
};
