import AirportShuttleIcon from "@material-ui/icons/AirportShuttle";
import ApartmentSharpIcon from "@material-ui/icons/ApartmentSharp";
import AttachMoneySharpIcon from "@material-ui/icons/AttachMoneySharp";
import BlurOnIcon from "@material-ui/icons/BlurOn";
import DescriptionIcon from "@material-ui/icons/Description";
import DescriptionOutlinedIcon from "@material-ui/icons/DescriptionOutlined";
import FastfoodIcon from "@material-ui/icons/Fastfood";
import FormatListNumberedIcon from "@material-ui/icons/FormatListNumbered";
import HomeSharpIcon from "@material-ui/icons/HomeSharp";
import LocalGroceryStoreIcon from "@material-ui/icons/LocalGroceryStore";
import InboxIcon from "@material-ui/icons/MoveToInbox";
import PeopleIcon from "@material-ui/icons/People";
import PeopleOutlineIcon from "@material-ui/icons/PeopleOutline";
import PersonIcon from "@material-ui/icons/Person";
import StarBorder from "@material-ui/icons/StarBorder";
import StoreMallDirectorySharpIcon from "@material-ui/icons/StoreMallDirectorySharp";
import React from "react";

export const MENU_LIST = [
  {
    id: "MENU_DEPARTMENT",
    path: "",
    isPublic: false,
    icon: "BlurOnIcon",
    text: "Quản lý phòng ban",
    child: [
      {
        id: "MENU_DEPARTMENT_LIST",
        path: "/departments/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS phòng ban",
        child: [],
      },
    ],
  },
  {
    id: "MENU_TMS",
    path: "",
    isPublic: false,
    icon: "BlurOnIcon",
    text: "Kiểm soát lộ trình",
    child: [
      {
        id: "MENU_TMS_GISMAP",
        path: "/tracklocations/gismap",
        isPublic: true,
        icon: "StarBorder",
        text: "Bản đồ",
        child: [],
      },
      {
        id: "MENU_TMS_LIST",
        path: "/tracklocations/list",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách",
        child: [],
      },
    ],
  },
  {
    id: "MENU_USER",
    path: "",
    isPublic: false,
    icon: "PersonIcon",
    text: "Tài khoản",
    child: [
      {
        id: "MENU_USER_CREATE",
        path: "/userlogin/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới",
        child: [],
      },
      {
        id: "MENU_USER_LIST",
        path: "/userlogin/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách",
        child: [],
      },
      {
        id: "MENU_USER_LIST",
        path: "/user/approve-register",
        isPublic: false,
        icon: "StarBorder",
        text: "Phê duyệt",
        child: [],
      },
    ],
  },
  {
    id: "MENU_ORDER",
    path: "",
    isPublic: false,
    icon: "DescriptionOutlinedIcon",
    text: "Đơn hàng",
    child: [
      {
        id: "MENU_ORDER_CREATE",
        path: "/orders/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới",
        child: [],
      },
      {
        id: "MENU_ORDER_LIST",
        path: "/orders/list",
        isPublic: false,
        icon: "StarBorder",
        text: "DS Đơn Hàng",
        child: [],
      },
    ],
  },
  {
    id: "MENU_INVOICE",
    path: "",
    isPublic: false,
    icon: "DescriptionIcon",
    text: "Hóa đơn",
    child: [
      {
        id: "MENU_INVOICE_CREATE",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới",
        child: [],
      },
      {
        id: "MENU_INVOICE_LIST",
        path: "/invoice-sales/list",
        isPublic: false,
        icon: "StarBorder",
        text: "DS hóa đơn thu",
        child: [],
      },
      {
        id: "MENU_INVOICE_LIST",
        path: "/customer-payment/list",
        isPublic: false,
        icon: "StarBorder",
        text: "DS KH thanh toán",
        child: [],
      },
    ],
  },
  {
    id: "MENU_UNPAID_INVOICE",
    path: "",
    isPublic: false,
    icon: "DescriptionIcon",
    text: "Báo cáo công nợ",
    child: [
      {
        id: "",
        path: "/distributor-unpaid-invoice/list",
        isPublic: true,
        icon: "StarBorder",
        text: "Công nợ của nhà phân phối",
        child: [],
      },
      {
        id: "",
        path: "/retail-outlet-unpaid-invoice/list",
        isPublic: true,
        icon: "StarBorder",
        text: "Công nợ của đại lí bán lẻ",
        child: [],
      },
    ],
  },
  {
    id: "MENU_SALES_ROUTE",
    path: "",
    isPublic: false,
    icon: "LocalGroceryStoreIcon",
    text: "Tuyến bán hàng",
    child: [
      {
        id: "",
        path: "/salesman/list",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách NVBH",
        child: [],
      },
      {
        id: "",
        path: "/salesman/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Tạo mới NVBH",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách khách hàng",
        child: [],
      },
      {
        id: "",
        path: "/salesroutes/plan",
        isPublic: true,
        icon: "StarBorder",
        text: "Kế hoạch tuyến",
        child: [],
      },
      {
        id: "",
        path: "/salesroutes/configs",
        isPublic: true,
        icon: "StarBorder",
        text: "Cấu hình tuyến",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Chi tiết tuyến",
        child: [],
      },
      {
        id: "",
        path: "/salesroutes/salesman-checkin-routes",
        isPublic: true,
        icon: "StarBorder",
        text: "Lịch sử check-in tuyến",
        child: [],
      },
    ],
  },
  {
    id: "MENU_SUPPLIER",
    path: "",
    isPublic: true,
    icon: "HomeSharpIcon",
    text: "QL nhà cung cấp",
    child: [
      {
        id: "",
        path: "/supplier/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS nhà cung cấp",
        child: [],
      },
      {
        id: "",
        path: "/supplier/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Tạo mới nhà cung cấp",
        child: [],
      },
    ],
  },
  {
    id: "MENU_PURCHASE_ORDER",
    path: "",
    isPublic: true,
    icon: "HomeSharpIcon",
    text: "Mua hàng",
    child: [
      {
        id: "",
        path: "/purchase-order/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS đơn mua",
        child: [],
      },
      {
        id: "",
        path: "/supplier/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS nhà cung cấp",
        child: [],
      },
    ],
  },
  {
    id: "MENU_PRODUCT_PRICE_SUPPLIER",
    path: "",
    isPublic: true,
    icon: "HomeSharpIcon",
    text: "Giá Mua hàng",
    child: [
      {
        id: "",
        path: "/product-price-supplier/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS giá mua",
        child: [],
      },
    ],
  },
  {
    id: "MENU_WAREHOUSE",
    path: "",
    isPublic: false,
    icon: "HomeSharpIcon",
    text: "QL Kho",
    child: [
      {
        id: "MENU_WAREHOUSE_IMPORT",
        path: "/inventory/import",
        isPublic: false,
        icon: "StarBorder",
        text: "Nhập kho",
        child: [],
      },
      {
        id: "MENU_WAREHOUSE_EXPORT",
        path: "/inventory/order",
        isPublic: false,
        icon: "StarBorder",
        text: "Xuất kho",
        child: [],
      },
      {
        id: "MENU_WAREHOUSE_INVENTORY_ITEM",
        path: "/inventory/list",
        isPublic: false,
        icon: "StarBorder",
        text: "QL tồn kho",
        child: [],
      },
    ],
  },
  {
    id: "MENU_TRANSPORT",
    path: "",
    isPublic: false,
    icon: "AirportShuttleIcon",
    text: "QL Vận chuyển",
    child: [
      {
        id: "",
        path: "/vehicle",
        isPublic: true,
        icon: "StarBorder",
        text: "DS Xe",
        child: [],
      },
      {
        id: "",
        path: "/driver/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới Tài xế",
        child: [],
      },
      {
        id: "",
        path: "/driver/list",
        isPublic: false,
        icon: "StarBorder",
        text: "DS Tài xế",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "DS khách hàng",
        child: [],
      },
      {
        id: "",
        path: "/shipment",
        isPublic: false,
        icon: "StarBorder",
        text: "DS đơn hàng vận chuyển",
        child: [],
      },
      {
        id: "",
        path: "/delivery-plan/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới đợt giao hàng",
        child: [],
      },
      {
        id: "",
        path: "/delivery-plan-list",
        isPublic: false,
        icon: "StarBorder",
        text: "DS đợt giao hàng",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "Lập kế hoạch giao hàng",
        child: [],
      },
      {
        id: "",
        path: "/solver-config-param",
        isPublic: false,
        icon: "StarBorder",
        text: "Cấu hình bộ giải",
        child: [],
      },
    ],
  },
  {
    id: "MENU_POST",
    path: "",
    isPublic: false,
    icon: "ApartmentSharpIcon",
    text: "QL chuyển phát bưu kiện",
    child: [
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "DS phương tiện",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "DS khách hàng",
        child: [],
      },
      {
        id: "",
        path: "/postoffice/list",
        isPublic: false,
        icon: "StarBorder",
        text: "DS bưu cục",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "DS đơn hàng chuyển phát",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới đợt chuyển phát",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "DS đợt chuyển phát",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "Lập kế hoạch thu gom bưu kiện",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: false,
        icon: "StarBorder",
        text: "Lập kế hoạch phát bưu kiện",
        child: [],
      },
    ],
  },
  {
    id: "MENU_PRODUCT",
    path: "",
    isPublic: false,
    icon: "FastfoodIcon",
    text: "QL sản phẩm",
    child: [
      {
        id: "MENU_PRODUCT_CREATE",
        path: "/products/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới sản phẩm",
        child: [],
      },
      {
        id: "MENU_PRODUCT_VIEW",
        path: "/products/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách SP",
        child: [],
      },
    ],
  },
  {
    id: "MENU_CUSTOMER",
    path: "",
    isPublic: false,
    icon: "PeopleOutlineIcon",
    text: "QL Khách hàng",
    child: [
      {
        id: "MENU_CUSTOMER_CREATE",
        path: "/customer/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới KH",
        child: [],
      },
      {
        id: "MENU_CUSTOMER_VIEW",
        path: "/customer/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách KH",
        child: [],
      },
    ],
  },
  {
    id: "MENU_RETAIL_OUTLET",
    path: "",
    isPublic: false,
    icon: "StoreMallDirectorySharpIcon",
    text: "QL đại lí bán lẻ",
    child: [
      {
        id: "MENU_CREATE_RETAIL_OUTLET",
        path: "/retailoutlet/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới ĐLBL",
        child: [],
      },
      {
        id: "MENU_VIEW_RETAIL_OUTLET",
        path: "/retailoutlet/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách ĐLBL",
        child: [],
      },
      {
        id: "MENU_VIEW_ALL_RETAIL_OUTLET",
        path: "/retailoutlet/listall",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách tất cả ĐLBL",
        child: [],
      },
    ],
  },
  {
    id: "MENU_USER",
    path: "",
    isPublic: false,
    icon: "PeopleIcon",
    text: "QL nhân viên bán hàng",
    child: [
      {
        id: "MENU_USER_CREATE",
        path: "/salesman/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới NVBH",
        child: [],
      },
      {
        id: "MENU_USER_LIST",
        path: "/salesman/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách NVBH",
        child: [],
      },
      {
        id: "MENU_USER_LIST",
        path: "/salesman/assign-salesman-2-distributor",
        isPublic: false,
        icon: "StarBorder",
        text: "Phân công NVBH cho NPP",
        child: [],
      },
      {
        id: "MENU_USER_LIST",
        path: "/salesman/assign-salesman-2-retail-outlet",
        isPublic: false,
        icon: "StarBorder",
        text: "Phân công NVBH phụ trách ĐLBL",
        child: [],
      },
    ],
  },
  {
    id: "MENU_DISTRIBUTOR",
    path: "",
    isPublic: false,
    icon: "ApartmentSharpIcon",
    text: "QL Nhà Phân Phối",
    child: [
      {
        id: "MENU_CREATE_DISTRIBUTOR",
        path: "/distributor/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Tạo mới NPP",
        child: [],
      },
      {
        id: "MENU_VIEW_DISTRIBUTOR",
        path: "/distributor/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách NPP",
        child: [],
      },
      {
        id: "MENU_VIEW_ALL_DISTRIBUTOR",
        path: "/distributor/listall",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách tất cả NPP",
        child: [],
      },
    ],
  },
  {
    id: "MENU_PRODUCT_PRICE",
    path: "",
    isPublic: false,
    icon: "AttachMoneySharpIcon",
    text: "QL giá sản phẩm",
    child: [
      {
        id: "MENU_PRODUCT_PRICE_CREATE",
        path: "/distributor/create",
        isPublic: false,
        icon: "StarBorder",
        text: "Thiết lập giá sản phẩm",
        child: [],
      },
      {
        id: "MENU_PRODUCT_VIEW",
        path: "/distributor/list",
        isPublic: false,
        icon: "StarBorder",
        text: "Danh sách SP",
        child: [],
      },
    ],
  },
  {
    id: "MENU_MAP",
    path: "",
    isPublic: false,
    icon: "InboxIcon",
    text: "QL vị trí, địa chỉ trên bản đồ",
    child: [
      {
        id: "",
        path: "/geo/list/location",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách vị trí",
        child: [],
      },
      {
        id: "",
        path: "/geo/list/distance-info",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách khoảng cách",
        child: [],
      },
    ],
  },
  {
    id: "MENU_SALES_REPORT",
    path: "",
    isPublic: false,
    icon: "FormatListNumberedIcon",
    text: "Báo cáo bán hàng",
    child: [
      {
        id: "",
        path: "/sale-reports-by-date",
        isPublic: true,
        icon: "StarBorder",
        text: "Doanh số theo ngày",
        child: [],
      },
      {
        id: "",
        path: "/sale-reports-by-customer",
        isPublic: true,
        icon: "StarBorder",
        text: "Doanh số theo khách hàng",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Doanh số theo nhà phân phối",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Doanh số theo nhân viên bán hàng",
        child: [],
      },
      {
        id: "",
        path: "/sale-reports-by-product",
        isPublic: true,
        icon: "StarBorder",
        text: "Doanh số theo sản phẩm",
        child: [],
      },
    ],
  },
  {
    id: "MENU_FACILITY_REPORT",
    path: "",
    isPublic: false,
    icon: "FormatListNumberedIcon",
    text: "Báo cáo kho",
    child: [
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Báo cáo tồn kho",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Xuất kho",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "Nhập kho",
        child: [],
      },
    ],
  },
  {
    id: "MENU_TMS_REPORT",
    path: "",
    isPublic: false,
    icon: "AirportShuttleIcon",
    text: "Báo cáo vận chuyển",
    child: [
      {
        id: "",
        path: "/transport-reports-by-driver",
        isPublic: true,
        icon: "StarBorder",
        text: "Báo cáo chuyến theo tài xế",
        child: [],
      },
      {
        id: "",
        path: "/transport-reports-by-customer",
        isPublic: true,
        icon: "StarBorder",
        text: "Báo cáo chuyến theo KH",
        child: [],
      },
      {
        id: "",
        path: "/transport-reports-by-facility",
        isPublic: true,
        icon: "StarBorder",
        text: "Báo cáo chuyến theo kho",
        child: [],
      },
    ],
  },
  {
    id: "MENU_TMS_CONTAINER",
    path: "",
    isPublic: false,
    icon: "AirportShuttleIcon",
    text: "Vận chuyển container",
    child: [
      {
        id: "",
        path: "/portfunc/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới bến cảng",
        child: [],
      },
      {
        id: "",
        path: "/portfunc/list",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách bến cảng",
        child: [],
      },
      {
        id: "",
        path: "/depottruckfunc/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới bãi đầu kéo",
        child: [],
      },
      {
        id: "",
        path: "/depottruckfunc/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS bãi đầu kéo",
        child: [],
      },
      {
        id: "",
        path: "/depottrailerfunc/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới bãi mooc",
        child: [],
      },
      {
        id: "",
        path: "/depottrailerfunc/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS bãi rơ mooc",
        child: [],
      },
      {
        id: "",
        path: "/depotcontainerfunc/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới bãi container",
        child: [],
      },
      {
        id: "",
        path: "/depotcontainerfunc/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS bãi container",
        child: [],
      },
      {
        id: "",
        path: "/containerfunc/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Tạo mới container",
        child: [],
      },
      {
        id: "",
        path: "/containerfunc/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS container",
        child: [],
      },
      {
        id: "",
        path: "/trailerfunc/create",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới rơ mooc",
        child: [],
      },
      {
        id: "",
        path: "/trailerfunc/list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS rơ mooc",
        child: [],
      },
      {
        id: "",
        path: "/create-request-transport-container-empty",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm yêu cầu chuyển container rỗng từ kho về bãi",
        child: [],
      },
      {
        id: "",
        path: "/list-request-transport-container-empty",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách đơn vận chuyển container rỗng từ kho đến bãi",
        child: [],
      },
      {
        id: "",
        path: "/create-request-transport-container-empty-export",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm yêu cầu chuyển container rỗng từ bãi về kho",
        child: [],
      },
      {
        id: "",
        path: "/list-request-transport-container-empty-export",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách đơn vận chuyển container rỗng từ bãi đến kho",
        child: [],
      },
      {
        id: "",
        path: "/create-request-transport-full-export",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới yêu cầu chuyển container đầy hàng từ kho ra cảng",
        child: [],
      },
      {
        id: "",
        path: "/list-request-transport-full-export",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách đơn vận chuyển container đầy hàng từ kho ra cảng ",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "DS đơn vận chuyển import empty",
        child: [],
      },
      {
        id: "",
        path: "/create-request-transport-container-to-warehouse",
        isPublic: true,
        icon: "StarBorder",
        text: "Thêm mới yêu cầu vận chuyển container đến kho",
        child: [],
      },
      {
        id: "",
        path: "/list-request-transport-container-to-warehouse",
        isPublic: true,
        icon: "StarBorder",
        text: "Danh sách đơn vận chuyển container đầy đến kho",
        child: [],
      },
      {
        id: "",
        path: "",
        isPublic: true,
        icon: "StarBorder",
        text: "DS đơn chuyển kho",
        child: [],
      },
    ],
  },
  {
    id: "MENU_TEACHING_ASSIGNMENT",
    path: "",
    isPublic: true,
    icon: "AirportShuttleIcon",
    text: "Phân công giảng dạy",
    child: [
      {
        id: "",
        path: "/edu/courses-list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS môn học",
        child: [],
      },
      {
        id: "",
        path: "/edu/teachers-list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS giáo viên",
        child: [],
      },
      {
        id: "",
        path: "/edu/classes-list",
        isPublic: true,
        icon: "StarBorder",
        text: "DS lớp",
        child: [],
      },
      {
        id: "",
        path: "/edu/assignment",
        isPublic: true,
        icon: "StarBorder",
        text: "DS phân công",
        child: [],
      },
    ],
  },
];
export const menuIconMap = new Map();
menuIconMap.set("InboxIcon", <InboxIcon />);
menuIconMap.set("StarBorder", <StarBorder />);
menuIconMap.set("PeopleIcon", <PeopleIcon />);
menuIconMap.set("AirportShuttleIcon", <AirportShuttleIcon />);
menuIconMap.set("PeopleOutlineIcon", <PeopleOutlineIcon />);
menuIconMap.set("PersonIcon", <PersonIcon />);
menuIconMap.set("FormatListNumberedIcon", <FormatListNumberedIcon />);
menuIconMap.set("DescriptionIcon", <DescriptionIcon />);
menuIconMap.set("DescriptionOutlinedIcon", <DescriptionOutlinedIcon />);
menuIconMap.set("ApartmentSharpIcon", <ApartmentSharpIcon />);
menuIconMap.set("AttachMoneySharpIcon", <AttachMoneySharpIcon />);
menuIconMap.set("StoreMallDirectorySharpIcon", <StoreMallDirectorySharpIcon />);
menuIconMap.set("HomeSharpIcon", <HomeSharpIcon />);
menuIconMap.set("FastfoodIcon", <FastfoodIcon />);
menuIconMap.set("LocalGroceryStoreIcon", <LocalGroceryStoreIcon />);
menuIconMap.set("BlurOnIcon", <BlurOnIcon />);
